// Backend/src/emergency/emergencyState.js

export const EMERGENCY_STATUS = {
  CALLING: "CALLING",

  AI_ANALYSIS: "AI_ANALYSIS",

  DISPATCHED: "DISPATCHED",

  EN_ROUTE_TO_USER: "EN_ROUTE_TO_USER",

  ARRIVED_AT_USER: "ARRIVED_AT_USER",

  PATIENT_PICKUP: "PATIENT_PICKUP",

  EN_ROUTE_TO_HOSPITAL: "EN_ROUTE_TO_HOSPITAL",

  ARRIVED_AT_HOSPITAL: "ARRIVED_AT_HOSPITAL",

  COMPLETED: "COMPLETED",

  REJECTED: "REJECTED",

  CANCELLED: "CANCELLED",

  AI_FAILED: "AI_FAILED",
};